### ISSUE TITLE
Visual Studio doesn't find my pester tests. 

### ISSUE THREAD

**Issue by sansin** [microsoft/poshtools#370]
I have the pester installed and using Visual studio 2012. 

As soon as I open my project, I see the below exception in the tests output.

------ Load Playlist started ------
========== Load Playlist finished (0:00:00) ==========
------ Discover test started ------
Searching for tests in [C:\Users\ssin\Perforce\ssin_V1_9488\DePester.ps1].
Searching for tests in [C:\Users\ssin\Perforce\ssin_V1_9488\resume_failed_initiation.ps1].
An exception occurred while test discoverer 'PowerShellTestDiscoverer' was loading tests. Exception: Object reference not set to an instance of an object.
========== Discover test finished: 0 found (0:00:00.9824952) ==========

If I open powershell command line and run the tests, it workes fine. 

Also, I have the same code and similar setup on another machine and there it works fine. 

Can someone help me resolve this issue?

**Comment by ASayre** [comment]
Hi @sansin ! Which version of the tools?  What version of Pester?

@adamdriscoll

**Comment by sansin** [comment]
Hi @AndreSayreMSFT . I saw the version number from the Changelog.md file and it says 2.1.0 and not exactly sure how to find version for tools. Can you please help me with that as well?

**Comment by ASayre** [comment]
Tools -> Extensions & Updates -> 
![image](https://cloud.githubusercontent.com/assets/10080679/7097542/6051ca50-df8b-11e4-8004-825b9b36fdaf.png)

That's quite an old version of Pester -- if you update Pester, do you still run into this issue?

**Comment by sansin** [comment]
Yea, I tried. but when I did, I ran into some other troubles. so again I went back to older version of Pester. 

PowerShell Tools for Visual Studio 2012 and Version 1.0.5

**Comment by adamdriscoll** [comment]
There have been some changes since 1.0.5 since around Pester support and while I had added support for the newer version of Pester, I'm sure some bugs were fixed in the discovery as well. I'll have to take a look. Do you have an example script that is failing?

**Comment by sansin** [comment]
Sure. Below is the script that is failing. 

#####################
Param(
    [Parameter(Mandatory=$true, Position=0, HelpMessage="What is the S3 key to resume load?")]
    [String]$s3_key_for_elt,
    [bool]$permit_concurrent_workflows = $false
)

$ErrorActionPreference = 'Stop'
$root_path = Split-Path -Parent $MyInvocation.MyCommand.Path
. "$root_path\src\shared\set_paths.ps1" -root_path $root_path
. "$script_path\logger.ps1"
. "$script_path\start_functions.ps1"
. "$shared_path\read_settings.ps1"

try {
    SetDefaultProxy $settings_xml.Settings.ProxyUrl
    if(-not $permit_concurrent_workflows) { WaitForNoOpenWorkflows $root_path $settings_xml.Settings.OpenWorkflowPollCount $settings_xml.Settings.OpenWorkflowPollIntervalSeconds }
    & $script_path\initiate_workflow.ps1 -root_path $root_path -s3_key $s3_key_for_elt -skip_transformations $false
} catch [Exception] {
    WriteLog $_.Exception
    exit 1
} finally {
    ClearDefaultProxy
}

**Comment by adamdriscoll** [comment]
I realized you're running VS2012 and with the recent changes were thinking of dropping support for tha t version of VS since 2015 was right around the corner. I haven't been able to reproduce your issue with our latest source so I'm assuming what ever changes are in the current dev branch solve the issue. I also looked at what it would take to build for 2012 and we have introduced breaking changes so it doesn't currently compile under the 2012 VS SDK. Adjusting the manifest to allow the extension to be install in VS2012 resulted in exceptions being thrown when starting up VS. 

If you have the ability and are willing to try on a VS2013 or VS2015CTP6 installation, please let me know if you also find that the script now is processed correctly.

I think the 2012 support is a seperate discussion.

**Comment by sansin** [comment]
Hi @adamdriscoll 

2 quick things to note here. 
1. I tried with the latest Pester(3.3.6) and still have the same exact error. (I am going to check with my infrastructure team if they can provide me a newer version of VS which I don't think is possible)
2. With same exact setup as I told before (Pester 2.1.0 and tools 1.0.5 and VS 2012) on an other windows machine, I am able to run the tests.

**Comment by adamdriscoll** [comment]
@sansin Can you try this build? It's the latest sources (with a few tweaks) for VS2012. https://onedrive.live.com/redir?resid=916FF62DEEDAF7E2!3256&authkey=!AHI9ZcFi_1bWEFI&ithint=file%2cvsix

**Comment by sansin** [comment]
Awesome @adamdriscoll . I installed the attached version and I am able to discover the tests in VS2012 now. Thank you for that. 

However, there seems to be a new problem now, when I try to "Run All", a whole bunmch of tests failed. I dont think they really have any problem, do you think anything to do with this newer pester ?

**Comment by adamdriscoll** [comment]
It could be. What error are you seeing in that is causing the failure?

**Comment by sansin** [comment]
to give you an example, I have a simple test script which has the following.

Describe "date_range extractor" {

```
Context "date_range no previous value" {

    Function BeginProcessLog{}
    Mock BeginProcessLog

    Function BuildQuery_AllRecords($table_with_schema, $column_list, $nolock){}
    Mock BuildQuery_AllRecords { "SOME QUERY" }

    It "date_range calls BeginProcessLog" {

        Assert-MockCalled BeginProcessLog

    }

    It "date_range calls BuildQuery_AllRecords, passing some global values" {

        Assert-MockCalled BuildQuery_AllRecords -parameterFilter {$table_with_schema -eq "MySchema.MyTable" -and $nolock -eq $true -and $column_list -eq $computed_columns}

    }
```

And now 2 tests failed with no reason. 

Test Name:  date_range no previous value It date_range calls BeginProcessLog
Test Outcome:   Failed
Test Duration:  0:00:00

Test Name:  date_range no previous value It date_range calls BuildQuery_AllRecords, passing some global values
Test Outcome:   Failed
Test Duration:  0:00:00

**Comment by adamdriscoll** [comment]
Strange. Can you look in the Output pane after running the tests and see if there is anything interesting in there?

**Comment by sansin** [comment]
Here is the output pane results. Nothing different that what I saw in test explorer. 

------ Run test started ------
Describing RunQuery
   Context Fake constructor functions
    [+] Attempts to run a query 636ms
Tests completed in 636ms
Passed: 1 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 589ms
    [+] tests whether the output path exists 49ms
    [+] creates the path if it doesn't exist 28ms
    [+] performs an extraction using bcp 11ms
    [+] checks the row count of the resulting file 42ms
    [+] gzips the resulting file 13ms
    [+] writes a log 24ms
   Context with pre_count
    [+] returns the row count 234ms
    [+] tests whether the output path exists 13ms
    [+] creates the path if it doesn't exist 10ms
    [+] performs an extraction using bcp 10ms
    [+] checks the row count of the resulting file 29ms
    [+] gzips the resulting file 13ms
    [+] writes a log 10ms
   Context with pre_count and chunk_number
    [+] returns the row count 243ms
    [+] tests whether the output path exists 37ms
    [+] creates the path if it doesn't exist 11ms
    [+] performs an extraction using bcp 12ms
    [+] checks the row count of the resulting file 48ms
    [+] gzips the resulting file 24ms
    [+] writes a log 10ms
Tests completed in 1.47s
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 244ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 11ms
    [+] checks the row count of the resulting file 12ms
    [+] gzips the resulting file 9ms
    [+] writes a log 9ms
   Context with pre_count
    [+] returns the row count 265ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 17ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 12ms
    [+] gzips the resulting file 75ms
    [+] writes a log 9ms
   Context with pre_count and chunk_number
    [+] returns the row count 201ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 13ms
    [+] gzips the resulting file 12ms
    [+] writes a log 9ms
Tests completed in 971ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 224ms
    [+] tests whether the output path exists 11ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 11ms
    [+] checks the row count of the resulting file 12ms
    [+] gzips the resulting file 9ms
    [+] writes a log 9ms
   Context with pre_count
    [+] returns the row count 185ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 14ms
    [+] gzips the resulting file 9ms
    [+] writes a log 9ms
   Context with pre_count and chunk_number
    [+] returns the row count 203ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 10ms
    [+] checks the row count of the resulting file 13ms
    [+] gzips the resulting file 9ms
    [+] writes a log 9ms
Tests completed in 799ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 228ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 11ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 11ms
    [+] gzips the resulting file 8ms
    [+] writes a log 8ms
   Context with pre_count
    [+] returns the row count 226ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 15ms
    [+] gzips the resulting file 12ms
    [+] writes a log 9ms
   Context with pre_count and chunk_number
    [+] returns the row count 189ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 13ms
    [+] gzips the resulting file 11ms
    [+] writes a log 9ms
Tests completed in 833ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 209ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 18ms
    [+] gzips the resulting file 9ms
    [+] writes a log 11ms
   Context with pre_count
    [+] returns the row count 188ms
    [+] tests whether the output path exists 13ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 10ms
    [+] checks the row count of the resulting file 14ms
    [+] gzips the resulting file 10ms
    [+] writes a log 10ms
   Context with pre_count and chunk_number
    [+] returns the row count 183ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 14ms
    [+] gzips the resulting file 10ms
    [+] writes a log 10ms
Tests completed in 782ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 253ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 8ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 14ms
    [+] gzips the resulting file 8ms
    [+] writes a log 7ms
   Context with pre_count
    [+] returns the row count 183ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 13ms
    [+] gzips the resulting file 9ms
    [+] writes a log 10ms
   Context with pre_count and chunk_number
    [+] returns the row count 189ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 14ms
    [+] gzips the resulting file 11ms
    [+] writes a log 9ms
Tests completed in 811ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 213ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 11ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 11ms
    [+] gzips the resulting file 8ms
    [+] writes a log 10ms
   Context with pre_count
    [+] returns the row count 264ms
    [+] tests whether the output path exists 8ms
    [+] creates the path if it doesn't exist 8ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 16ms
    [+] gzips the resulting file 8ms
    [+] writes a log 8ms
   Context with pre_count and chunk_number
    [+] returns the row count 181ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 14ms
    [+] checks the row count of the resulting file 14ms
    [+] gzips the resulting file 9ms
    [+] writes a log 9ms
Tests completed in 847ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 218ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 8ms
    [+] performs an extraction using bcp 11ms
    [+] checks the row count of the resulting file 12ms
    [+] gzips the resulting file 8ms
    [+] writes a log 8ms
   Context with pre_count
    [+] returns the row count 197ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 20ms
    [+] gzips the resulting file 8ms
    [+] writes a log 9ms
   Context with pre_count and chunk_number
    [+] returns the row count 227ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 13ms
    [+] gzips the resulting file 11ms
    [+] writes a log 10ms
Tests completed in 834ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 220ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 11ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 11ms
    [+] gzips the resulting file 8ms
    [+] writes a log 8ms
   Context with pre_count
    [+] returns the row count 218ms
    [+] tests whether the output path exists 15ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 13ms
    [+] gzips the resulting file 11ms
    [+] writes a log 9ms
   Context with pre_count and chunk_number
    [+] returns the row count 186ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 14ms
    [+] gzips the resulting file 9ms
    [+] writes a log 9ms
Tests completed in 812ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 211ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 8ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 19ms
    [+] gzips the resulting file 13ms
    [+] writes a log 8ms
   Context with pre_count
    [+] returns the row count 177ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 8ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 12ms
    [+] gzips the resulting file 8ms
    [+] writes a log 9ms
   Context with pre_count and chunk_number
    [+] returns the row count 258ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 14ms
    [+] gzips the resulting file 8ms
    [+] writes a log 8ms
Tests completed in 835ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 210ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 8ms
    [+] performs an extraction using bcp 10ms
    [+] checks the row count of the resulting file 19ms
    [+] gzips the resulting file 9ms
    [+] writes a log 10ms
   Context with pre_count
    [+] returns the row count 203ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 8ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 13ms
    [+] gzips the resulting file 9ms
    [+] writes a log 9ms
   Context with pre_count and chunk_number
    [+] returns the row count 294ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 14ms
    [+] checks the row count of the resulting file 13ms
    [+] gzips the resulting file 9ms
    [+] writes a log 9ms
Tests completed in 903ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 210ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 19ms
    [+] gzips the resulting file 14ms
    [+] writes a log 14ms
   Context with pre_count
    [+] returns the row count 233ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 10ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 13ms
    [+] gzips the resulting file 11ms
    [+] writes a log 9ms
   Context with pre_count and chunk_number
    [+] returns the row count 252ms
    [+] tests whether the output path exists 16ms
    [+] creates the path if it doesn't exist 11ms
    [+] performs an extraction using bcp 11ms
    [+] checks the row count of the resulting file 13ms
    [+] gzips the resulting file 12ms
    [+] writes a log 10ms
Tests completed in 914ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 219ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 13ms
    [+] performs an extraction using bcp 10ms
    [+] checks the row count of the resulting file 14ms
    [+] gzips the resulting file 17ms
    [+] writes a log 10ms
   Context with pre_count
    [+] returns the row count 218ms
    [+] tests whether the output path exists 11ms
    [+] creates the path if it doesn't exist 10ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 18ms
    [+] gzips the resulting file 14ms
    [+] writes a log 9ms
   Context with pre_count and chunk_number
    [+] returns the row count 194ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 11ms
    [+] performs an extraction using bcp 10ms
    [+] checks the row count of the resulting file 14ms
    [+] gzips the resulting file 9ms
    [+] writes a log 11ms
Tests completed in 850ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 247ms
    [+] tests whether the output path exists 11ms
    [+] creates the path if it doesn't exist 13ms
    [+] performs an extraction using bcp 12ms
    [+] checks the row count of the resulting file 12ms
    [+] gzips the resulting file 8ms
    [+] writes a log 9ms
   Context with pre_count
    [+] returns the row count 194ms
    [+] tests whether the output path exists 11ms
    [+] creates the path if it doesn't exist 10ms
    [+] performs an extraction using bcp 15ms
    [+] checks the row count of the resulting file 17ms
    [+] gzips the resulting file 12ms
    [+] writes a log 10ms
   Context with pre_count and chunk_number
    [+] returns the row count 232ms
    [+] tests whether the output path exists 8ms
    [+] creates the path if it doesn't exist 10ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 12ms
    [+] gzips the resulting file 9ms
    [+] writes a log 10ms
Tests completed in 878ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 231ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 11ms
    [+] checks the row count of the resulting file 12ms
    [+] gzips the resulting file 9ms
    [+] writes a log 9ms
   Context with pre_count
    [+] returns the row count 185ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 14ms
    [+] gzips the resulting file 9ms
    [+] writes a log 8ms
   Context with pre_count and chunk_number
    [+] returns the row count 234ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 13ms
    [+] gzips the resulting file 14ms
    [+] writes a log 13ms
Tests completed in 844ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 217ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 10ms
    [+] checks the row count of the resulting file 11ms
    [+] gzips the resulting file 9ms
    [+] writes a log 8ms
   Context with pre_count
    [+] returns the row count 216ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 15ms
    [+] gzips the resulting file 9ms
    [+] writes a log 9ms
   Context with pre_count and chunk_number
    [+] returns the row count 235ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 16ms
    [+] gzips the resulting file 9ms
    [+] writes a log 10ms
Tests completed in 857ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 219ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 14ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 12ms
    [+] gzips the resulting file 8ms
    [+] writes a log 11ms
   Context with pre_count
    [+] returns the row count 216ms
    [+] tests whether the output path exists 8ms
    [+] creates the path if it doesn't exist 8ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 15ms
    [+] gzips the resulting file 8ms
    [+] writes a log 9ms
   Context with pre_count and chunk_number
    [+] returns the row count 186ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 12ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 15ms
    [+] gzips the resulting file 9ms
    [+] writes a log 9ms
Tests completed in 816ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 264ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 10ms
    [+] performs an extraction using bcp 11ms
    [+] checks the row count of the resulting file 12ms
    [+] gzips the resulting file 8ms
    [+] writes a log 8ms
   Context with pre_count
    [+] returns the row count 180ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 14ms
    [+] gzips the resulting file 9ms
    [+] writes a log 9ms
   Context with pre_count and chunk_number
    [+] returns the row count 178ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 13ms
    [+] gzips the resulting file 10ms
    [+] writes a log 9ms
Tests completed in 807ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 219ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 8ms
    [+] performs an extraction using bcp 10ms
    [+] checks the row count of the resulting file 11ms
    [+] gzips the resulting file 10ms
    [+] writes a log 12ms
   Context with pre_count
    [+] returns the row count 191ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 14ms
    [+] gzips the resulting file 9ms
    [+] writes a log 10ms
   Context with pre_count and chunk_number
    [+] returns the row count 217ms
    [+] tests whether the output path exists 12ms
    [+] creates the path if it doesn't exist 10ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 13ms
    [+] gzips the resulting file 10ms
    [+] writes a log 9ms
Tests completed in 820ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 214ms
    [+] tests whether the output path exists 17ms
    [+] creates the path if it doesn't exist 10ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 13ms
    [+] gzips the resulting file 8ms
    [+] writes a log 8ms
   Context with pre_count
    [+] returns the row count 209ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 14ms
    [+] gzips the resulting file 9ms
    [+] writes a log 9ms
   Context with pre_count and chunk_number
    [+] returns the row count 225ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 16ms
    [+] gzips the resulting file 9ms
    [+] writes a log 9ms
Tests completed in 841ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing StreamQueryToCSV
   Context without pre_count
    [+] returns the row count 215ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 13ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 12ms
    [+] gzips the resulting file 8ms
    [+] writes a log 9ms
   Context with pre_count
    [+] returns the row count 228ms
    [+] tests whether the output path exists 9ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 8ms
    [+] checks the row count of the resulting file 13ms
    [+] gzips the resulting file 12ms
    [+] writes a log 9ms
   Context with pre_count and chunk_number
    [+] returns the row count 177ms
    [+] tests whether the output path exists 10ms
    [+] creates the path if it doesn't exist 9ms
    [+] performs an extraction using bcp 9ms
    [+] checks the row count of the resulting file 12ms
    [+] gzips the resulting file 8ms
    [+] writes a log 10ms
Tests completed in 809ms
Passed: 21 Failed: 0 Skipped: 0 Pending: 0

Describing VerifyCounts
   Context without pre-count
    [+] writes an informative log message if they differ 176ms
   Context with pre-count
    [+] throws an exception if pre_count and reported_count don't match 162ms
    [-] writes an informative log message if reported_count and output_lines differ 20ms
      Expected WriteLog to be called at least 1 times but was called 0 times
      at line: 518 in C:\Users\ssingarapu\Documents\WindowsPowerShell\Modules\Pester\Functions\Mock.ps1
Tests completed in 358ms
Passed: 2 Failed: 1 Skipped: 0 Pending: 0

Describing VerifyCounts
   Context without pre-count
    [+] writes an informative log message if they differ 181ms
   Context with pre-count
    [+] throws an exception if pre_count and reported_count don't match 156ms
    [-] writes an informative log message if reported_count and output_lines differ 9ms
      Expected WriteLog to be called at least 1 times but was called 0 times
      at line: 518 in C:\Users\ssingarapu\Documents\WindowsPowerShell\Modules\Pester\Functions\Mock.ps1
Tests completed in 347ms
Passed: 2 Failed: 1 Skipped: 0 Pending: 0

Describing VerifyCounts
   Context without pre-count
    [+] writes an informative log message if they differ 170ms
   Context with pre-count
    [+] throws an exception if pre_count and reported_count don't match 144ms
    [-] writes an informative log message if reported_count and output_lines differ 10ms
      Expected WriteLog to be called at least 1 times but was called 0 times
      at line: 518 in C:\Users\ssingarapu\Documents\WindowsPowerShell\Modules\Pester\Functions\Mock.ps1
Tests completed in 324ms
Passed: 2 Failed: 1 Skipped: 0 Pending: 0

Describing GZipCSVFile
   Context one param, just create .gz version
    [-] attempts compression 254ms
      Expected Compress-GZip to be called at least 1 times but was called 0 times
      at line: 518 in C:\Users\ssingarapu\Documents\WindowsPowerShell\Modules\Pester\Functions\Mock.ps1
    [+] deletes the file 10ms
   Context two params, specified output
    [-] attempts compression 167ms
      Expected Compress-GZip to be called at least 1 times but was called 0 times
      at line: 518 in C:\Users\ssingarapu\Documents\WindowsPowerShell\Modules\Pester\Functions\Mock.ps1
    [+] deletes the file 8ms
Tests completed in 442ms
Passed: 2 Failed: 2 Skipped: 0 Pending: 0

Describing GZipCSVFile
   Context one param, just create .gz version
    [-] attempts compression 174ms
      Expected Compress-GZip to be called at least 1 times but was called 0 times
      at line: 518 in C:\Users\ssingarapu\Documents\WindowsPowerShell\Modules\Pester\Functions\Mock.ps1
    [+] deletes the file 10ms
   Context two params, specified output
    [-] attempts compression 198ms
      Expected Compress-GZip to be called at least 1 times but was called 0 times
      at line: 518 in C:\Users\ssingarapu\Documents\WindowsPowerShell\Modules\Pester\Functions\Mock.ps1
    [+] deletes the file 8ms
Tests completed in 392ms
Passed: 2 Failed: 2 Skipped: 0 Pending: 0

Describing GZipCSVFile
   Context one param, just create .gz version
    [-] attempts compression 169ms
      Expected Compress-GZip to be called at least 1 times but was called 0 times
      at line: 518 in C:\Users\ssingarapu\Documents\WindowsPowerShell\Modules\Pester\Functions\Mock.ps1
    [+] deletes the file 9ms
   Context two params, specified output
    [-] attempts compression 215ms
      Expected Compress-GZip to be called at least 1 times but was called 0 times
      at line: 518 in C:\Users\ssingarapu\Documents\WindowsPowerShell\Modules\Pester\Functions\Mock.ps1
    [+] deletes the file 8ms
Tests completed in 404ms
Passed: 2 Failed: 2 Skipped: 0 Pending: 0

Describing GZipCSVFile
   Context one param, just create .gz version
    [-] attempts compression 172ms
      Expected Compress-GZip to be called at least 1 times but was called 0 times
      at line: 518 in C:\Users\ssingarapu\Documents\WindowsPowerShell\Modules\Pester\Functions\Mock.ps1
    [+] deletes the file 10ms
   Context two params, specified output
    [-] attempts compression 151ms
      Expected Compress-GZip to be called at least 1 times but was called 0 times
      at line: 518 in C:\Users\ssingarapu\Documents\WindowsPowerShell\Modules\Pester\Functions\Mock.ps1
    [+] deletes the file 9ms
Tests completed in 343ms
Passed: 2 Failed: 2 Skipped: 0 Pending: 0

Describing ExtractWithBCP
   Context Successful username/password BCP with 0 rows
    [+] should call BCP with the expected parameters 190ms
    [+] should return 0 rows copied 10ms
   Context Successful AD BCP with 0 rows
    [+] should call BCP with the expected parameters 212ms
    [+] should return 0 rows copied 7ms
   Context Successful AD BCP with 1000 rows
    [+] should return 1000 rows copied 147ms
   Context AD BCP with non-zero exit code
    [+] throws an exception 141ms
   Context AD BCP with unexpected response
    [+] throws an exception 150ms
   Context AD BCP with error response
    [+] throws an exception 156ms
   Context AD BCP with other exception
    [+] throws an exception 150ms
Tests completed in 1.17s
Passed: 9 Failed: 0 Skipped: 0 Pending: 0

Describing ExtractWithBCP
   Context Successful username/password BCP with 0 rows
    [+] should call BCP with the expected parameters 184ms
    [+] should return 0 rows copied 9ms
   Context Successful AD BCP with 0 rows
    [+] should call BCP with the expected parameters 211ms
    [+] should return 0 rows copied 8ms
   Context Successful AD BCP with 1000 rows
    [+] should return 1000 rows copied 160ms
   Context AD BCP with non-zero exit code
    [+] throws an exception 160ms
   Context AD BCP with unexpected response
    [+] throws an exception 151ms
   Context AD BCP with error response
    [+] throws an exception 169ms
   Context AD BCP with other exception
    [+] throws an exception 158ms
Tests completed in 1.22s
Passed: 9 Failed: 0 Skipped: 0 Pending: 0

Describing ExtractWithBCP
   Context Successful username/password BCP with 0 rows
    [+] should call BCP with the expected parameters 166ms
    [+] should return 0 rows copied 10ms
   Context Successful AD BCP with 0 rows
    [+] should call BCP with the expected parameters 208ms
    [+] should return 0 rows copied 6ms
   Context Successful AD BCP with 1000 rows
    [+] should return 1000 rows copied 151ms
   Context AD BCP with non-zero exit code
    [+] throws an exception 156ms
   Context AD BCP with unexpected response
    [+] throws an exception 156ms
   Context AD BCP with error response
    [+] throws an exception 151ms
   Context AD BCP with other exception
    [+] throws an exception 147ms
Tests completed in 1.16s
Passed: 9 Failed: 0 Skipped: 0 Pending: 0

Describing ExtractWithBCP
   Context Successful username/password BCP with 0 rows
    [+] should call BCP with the expected parameters 284ms
    [+] should return 0 rows copied 10ms
   Context Successful AD BCP with 0 rows
    [+] should call BCP with the expected parameters 198ms
    [+] should return 0 rows copied 7ms
   Context Successful AD BCP with 1000 rows
    [+] should return 1000 rows copied 154ms
   Context AD BCP with non-zero exit code
    [+] throws an exception 164ms
   Context AD BCP with unexpected response
    [+] throws an exception 150ms
   Context AD BCP with error response
    [+] throws an exception 155ms
   Context AD BCP with other exception
    [+] throws an exception 146ms
Tests completed in 1.27s
Passed: 9 Failed: 0 Skipped: 0 Pending: 0

Describing ExtractWithBCP
   Context Successful username/password BCP with 0 rows
    [+] should call BCP with the expected parameters 225ms
    [+] should return 0 rows copied 10ms
   Context Successful AD BCP with 0 rows
    [+] should call BCP with the expected parameters 184ms
    [+] should return 0 rows copied 7ms
   Context Successful AD BCP with 1000 rows
    [+] should return 1000 rows copied 154ms
   Context AD BCP with non-zero exit code
    [+] throws an exception 149ms
   Context AD BCP with unexpected response
    [+] throws an exception 142ms
   Context AD BCP with error response
    [+] throws an exception 172ms
   Context AD BCP with other exception
    [+] throws an exception 153ms
Tests completed in 1.2s
Passed: 9 Failed: 0 Skipped: 0 Pending: 0

Describing ExtractWithBCP
   Context Successful username/password BCP with 0 rows
    [+] should call BCP with the expected parameters 172ms
    [+] should return 0 rows copied 9ms
   Context Successful AD BCP with 0 rows
    [+] should call BCP with the expected parameters 157ms
    [+] should return 0 rows copied 7ms
   Context Successful AD BCP with 1000 rows
    [+] should return 1000 rows copied 153ms
   Context AD BCP with non-zero exit code
    [+] throws an exception 151ms
   Context AD BCP with unexpected response
    [+] throws an exception 147ms
   Context AD BCP with error response
    [+] throws an exception 164ms
   Context AD BCP with other exception
    [+] throws an exception 192ms
Tests completed in 1.16s
Passed: 9 Failed: 0 Skipped: 0 Pending: 0

Describing ExtractWithBCP
   Context Successful username/password BCP with 0 rows
    [+] should call BCP with the expected parameters 167ms
    [+] should return 0 rows copied 9ms
   Context Successful AD BCP with 0 rows
    [+] should call BCP with the expected parameters 155ms
    [+] should return 0 rows copied 7ms
   Context Successful AD BCP with 1000 rows
    [+] should return 1000 rows copied 144ms
   Context AD BCP with non-zero exit code
    [+] throws an exception 158ms
   Context AD BCP with unexpected response
    [+] throws an exception 157ms
   Context AD BCP with error response
    [+] throws an exception 150ms
   Context AD BCP with other exception
    [+] throws an exception 159ms
Tests completed in 1.11s
Passed: 9 Failed: 0 Skipped: 0 Pending: 0

========== Run test finished: 36 run (0:00:54.7584753) ==========

**Comment by ASayre** [comment]
Related to https://github.com/adamdriscoll/poshtools/pull/220

**Comment by jinglouMSFT** [comment]
This has been fixed. See adamdriscoll#220.
@sansin - Did the fix work for you?

**Comment by sansin** [comment]
Didn't check it yet. I will check it and post you the update.

**Comment by HuanhuanSunMSFT** [comment]
Hi @sansin, please reactivate it if this still repros
